[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "prettytable>=3.16.0",
    "python-dotenv==1.0.1",
    "sympy>=1.14.0",
    "tabulate>=0.9.0",
]
